name: Test Project

on:
  pull_request:
    branches:
      - uat

  jobs:
    test:
      run-on: debian-latest
      container:
        image: node:20
      steps:
        - users: actions/checkout@v3
          with:
            node-version: 20
        - run: npm ci
        - run: npm test
        - run: npm build 
